hw_aht10_func.c
pthread_mutex_t mutex
Referenced by compute_temperature, connection_handler, read_sensor.
pthread_cond_t cond
Referenced by compute_temperature, connection_handler, read_sensor.
int data_ready
Referenced by compute_temperature, connection_handler, read_sensor.
float temperature
Referenced by compute_temperature, send_message.
int validate_inputs(int argc, char **argv)
Referenced by main.
char * get_data_from_sensor(char *device_name, int dev_addr)
Referenced by read_sensor.
float compute_temperature_celsius(char *data)
Referenced by compute_temperature.
int start_listener(unsigned short port)
References MAX_SIZE.
Referenced by main.
void * read_sensor(void *arg)
References cond, SensorInfo::data, data_ready, SensorInfo::dev_address, SensorInfo::dev_name, e_computing, get_data_from_sensor, mutex, sensor_info.
Referenced by main.
void * compute_temperature(void *arg)
References compute_temperature_celsius, cond, SensorInfo::data, data_ready, e_computing, e_ready, mutex, sensor_info, temperature.
Referenced by main.
void send_message(int client_socket)
References MAX_SIZE, temperature.
Referenced by connection_handler.
void * connection_handler(void *socket_desc)
References cond, data_ready, e_gathering, e_ready, mutex, send_message.
Referenced by main.