hw_aht10_func.h
MAX_SIZE
Referenced by send_message, start_listener.
threads_states
SensorInfo sensor_info
Sensor information structure
Referenced by compute_temperature, main, read_sensor.
pthread_mutex_t mutex
Mutex for thread synchronization (prevents deadlocks)
Referenced by compute_temperature, connection_handler, main, read_sensor.
pthread_cond_t cond
Condition variable for thread synchronization (prevents race conditions)
Referenced by compute_temperature, connection_handler, main, read_sensor.
int validate_inputs(int, char **)
Referenced by main.
int start_listener(unsigned short)
References MAX_SIZE.
Referenced by main.
char * get_data_from_sensor(char *, int)
Referenced by read_sensor.
float compute_temperature_celsius(char *)
Referenced by compute_temperature.
void send_message(int)
References MAX_SIZE, temperature.
Referenced by connection_handler.
void * read_sensor(void *)
References cond, SensorInfo::data, data_ready, SensorInfo::dev_address, SensorInfo::dev_name, e_computing, get_data_from_sensor, mutex, sensor_info.
Referenced by main.
void * compute_temperature(void *)
References compute_temperature_celsius, cond, SensorInfo::data, data_ready, e_computing, e_ready, mutex, sensor_info, temperature.
Referenced by main.
void * connection_handler(void *)
References cond, data_ready, e_gathering, e_ready, mutex, send_message.
Referenced by main.