.TH "C:/Users/fouri/Downloads/honeywell_assessment/src Directory Reference" 3 "Version 1" "Honeywell Linux Assessment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/fouri/Downloads/honeywell_assessment/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhw_aht10_func\&.c\fP"
.br
.ti -1c
.RI "file \fBhw_aht10_func\&.h\fP"
.br
.ti -1c
.RI "file \fBhw_aht10_get_temp\&.c\fP"
.br
.ti -1c
.RI "file \fBhw_aht10_temperature_server\&.c\fP"
.br
.in -1c
