.TH "hw_aht10_func.h" 3 "Version Sr Advanced Embedded Engr." "Honeywell Linux Assessment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hw_aht10_func.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSensorInfo\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_SIZE\fP   256"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBthreads_states\fP { \fBe_gathering\fP, \fBe_computing\fP, \fBe_ready\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBvalidate_inputs\fP (int, char **)"
.br
.ti -1c
.RI "int \fBstart_listener\fP (unsigned short)"
.br
.ti -1c
.RI "char * \fBget_data_from_sensor\fP (char *, int)"
.br
.ti -1c
.RI "float \fBcompute_temperature_celsius\fP (char *)"
.br
.ti -1c
.RI "void \fBsend_message\fP (int)"
.br
.ti -1c
.RI "void * \fBread_sensor\fP (void *)"
.br
.ti -1c
.RI "void * \fBcompute_temperature\fP (void *)"
.br
.ti -1c
.RI "void * \fBconnection_handler\fP (void *)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSensorInfo\fP \fBsensor_info\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_SIZE   256"

.PP
Definition at line \fB4\fP of file \fBhw_aht10_func\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBthreads_states\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIe_gathering \fP\fP
.TP
\fB\fIe_computing \fP\fP
.TP
\fB\fIe_ready \fP\fP
.PP
Definition at line \fB16\fP of file \fBhw_aht10_func\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void * compute_temperature (void * arg)"

.PP
Definition at line \fB152\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "float compute_temperature_celsius (char * data)"

.PP
Definition at line \fB103\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "void * connection_handler (void * socket_desc)"

.PP
Definition at line \fB175\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "char * get_data_from_sensor (char * device_name, int dev_addr)"

.PP
Definition at line \fB41\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "void * read_sensor (void * arg)"

.PP
Definition at line \fB136\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "void send_message (int client_socket)"

.PP
Definition at line \fB168\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "int start_listener (unsigned short port)"

.PP
Definition at line \fB111\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "int validate_inputs (int argc, char ** argv)"

.PP
Definition at line \fB19\fP of file \fBhw_aht10_func\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "pthread_cond_t cond\fR [extern]\fP"
Condition variable for thread synchronization (prevents race conditions) 
.PP
Definition at line \fB15\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "pthread_mutex_t mutex\fR [extern]\fP"
Mutex for thread synchronization (prevents deadlocks) 
.PP
Definition at line \fB14\fP of file \fBhw_aht10_func\&.c\fP\&.
.SS "\fBSensorInfo\fP sensor_info\fR [extern]\fP"
Sensor information structure 
.PP
Definition at line \fB12\fP of file \fBhw_aht10_temperature_server\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Honeywell Linux Assessment from the source code\&.
