.TH "SensorInfo" 3 "Version Sr Advanced Embedded Engr." "Honeywell Linux Assessment" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensorInfo
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hw_aht10_func\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBdev_name\fP [\fBMAX_SIZE\fP]"
.br
.ti -1c
.RI "int \fBdev_address\fP"
.br
.ti -1c
.RI "char \fBdata\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBhw_aht10_func\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char data[6]"

.PP
Definition at line \fB9\fP of file \fBhw_aht10_func\&.h\fP\&.
.SS "int dev_address"

.PP
Definition at line \fB8\fP of file \fBhw_aht10_func\&.h\fP\&.
.SS "char dev_name[\fBMAX_SIZE\fP]"

.PP
Definition at line \fB7\fP of file \fBhw_aht10_func\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Honeywell Linux Assessment from the source code\&.
